name: Hiper Scraper Nuvoxtoons
on:
  workflow_dispatch:

jobs:
  setup_master:
    runs-on: ubuntu-latest
    outputs:
      master_token: ${{ steps.get_token.outputs.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalando Motores (Setup)
        run: npm install
      - id: get_token
        name: Executando Login Mestre
        run: |
          TOKEN=$(node master_login.js)
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

  scrape_mangas:
    needs: setup_master
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      fail-fast: false
    env:
      TOKEN_AUTH: ${{ needs.setup_master.outputs.master_token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalando Motores de Proxy (Jobs)
        run: npm install
      - run: mkdir -p resultados
      - run: node bot_scraper.js ${{ matrix.part }}
      - uses: actions/upload-artifact@v4
        with:
          name: Extrato_Lote_${{ matrix.part }}
          path: resultados/resultado_job_${{ matrix.part }}.json
          retention-days: 3
